Repository pingcap/tipocket, pull requests merged in 2020-04, with the labels that each got.

#170 rename tikv config file
  config/tikv.debug.toml
Labels: status/can-merge

#168 control: refactor nemesis logs
  cmd/util/suit.go
  pkg/cluster/types/cluster.go
  pkg/control/control.go
  pkg/core/nemesis.go
  pkg/nemesis/container_kill.go
  pkg/nemesis/iochaos.go
  pkg/nemesis/kill.go
  pkg/nemesis/leader_shuffle.go
  pkg/nemesis/nemesis.go
  pkg/nemesis/netem_chaos.go
  pkg/nemesis/network_partition.go
  pkg/nemesis/pd_scheduler.go
  pkg/nemesis/pod_kill.go
  pkg/nemesis/scaling.go
  pkg/nemesis/time_chaos.go
Labels: status/can-merge

#171 fix v_bank Step method
  tests/vbank/v_bank.go
Labels: status/can-merge

#162 Refactor recommendation to an interface
  argo/template/cdc.yaml
  argo/workflow/cdc.yaml
  cmd/abtest/main.go
  cmd/bank/main.go
  cmd/bank2/main.go
  cmd/block-writer/main.go
  cmd/cdc-pocket/main.go
  cmd/crud/main.go
  cmd/deadlock-detector/main.go
  cmd/ledger/main.go
  cmd/on-dup/main.go
  cmd/pocket/main.go
  cmd/read-stress/main.go
  cmd/region-available/main.go
  cmd/sqllogic/main.go
  cmd/tidb/main.go
  cmd/tiflash-pocket/main.go
  cmd/tpcc/main.go
  cmd/txn-rand-pessimistic/main.go
  cmd/util/suit.go
  cmd/vbank/main.go
  go.sum
  pkg/cluster/k8s.go
  pkg/cluster/local_cluster.go
  pkg/cluster/types/cluster.go
  pkg/cluster/types/interface.go
  pkg/test-infra/abtest/operation.go
  pkg/test-infra/abtest/recommend.go
  pkg/test-infra/binlog/operation.go
  pkg/test-infra/binlog/recommend.go
  pkg/test-infra/cdc/operation.go
  pkg/test-infra/cdc/recommend.go
  pkg/test-infra/clusters.go
  pkg/test-infra/fixture/abtest.go
  pkg/test-infra/fixture/cdc.go
  pkg/test-infra/fixture/fixture.go
  pkg/test-infra/tests/client.go
  pkg/test-infra/tidb/drainer.go
  pkg/test-infra/tidb/operation.go
  pkg/test-infra/tidb/recommend.go
  pkg/test-infra/tiflash/operation.go
  pkg/test-infra/tiflash/recommend.go
  pkg/test-infra/util/util.go
Labels: status/can-merge

#179 argo: update template
  argo/cron/bank.yaml
  argo/cron/ledger.yaml
  argo/cron/sc_bank.yaml
  argo/cron/sc_bank2.yaml
  argo/cron/vbank.yaml
  argo/template/bank.yaml
  argo/template/export-logs.yaml
  argo/workflow/abtest-chunk-rpc.yaml
  argo/workflow/abtest-plan-cache.yaml
  argo/workflow/abtest-tmp-storage.yaml
  argo/workflow/abtest.yaml
  argo/workflow/bank.yaml
  argo/workflow/binlog.yaml
  argo/workflow/block-writer.yaml
  argo/workflow/cdc.yaml
  argo/workflow/ledger.yaml
  argo/workflow/read-stress-unify-all.yaml
  argo/workflow/region-available.yaml
  argo/workflow/sc_bank.yaml
  argo/workflow/sc_bank2.yaml
  argo/workflow/sqllogic.yaml
  argo/workflow/tiflash.yaml
  argo/workflow/tpcc.yaml
  argo/workflow/txn-rand-pessimistic.yaml
  argo/workflow/vbank.yaml
Labels: status/can-merge

#158 add rawkv-linearizability test
  Makefile
  argo/template/rawkv-linearizability.yaml
  argo/workflow/rawkv-linearizability.yaml
  cmd/rawkv-linearizability/main.go
  cmd/util/suit.go
  db/tidb/bank.go
  db/tidb/bank_test.go
  db/tidb/long_fork.go
  db/tidb/multi_bank.go
  db/tidb/sequential.go
  db/tidb/tpcc.go
  go.mod
  go.sum
  pkg/check/porcupine/porcupine.go
  pkg/core/client.go
  pkg/history/history.go
  pkg/history/history_test.go
  pkg/history/noop.go
  pkg/model/cas_register.go
  pkg/model/register.go
  pkg/model/register_test.go
  pkg/pocket/creator/creator.go
  tests/bank/bank.go
  tests/bank2/bank2.go
  tests/block-writer/blockwriter.go
  tests/crud/crud.go
  tests/ledger/ledger.go
  tests/ondup/ondup.go
  tests/pessimistic/controller.go
  tests/pessimistic/deadlock/leader_change.go
  tests/rawkv-linearizability/rawkv_linearizability.go
  tests/read-stress/stress.go
  tests/region-available/region_available_detector.go
  tests/sqllogictest/client.go
  tests/vbank/v_bank.go
  util/util.go
Labels: status/can-merge

#194 Cluster: fix incorrect node port finding
  pkg/control/control.go
  pkg/nemesis/kill.go
  pkg/test-infra/binlog/operation.go
  pkg/test-infra/cdc/operation.go
  pkg/test-infra/tidb/operation.go
  pkg/test-infra/tiflash/operation.go
  pkg/test-infra/util/util.go
Labels: status/can-merge, type/bug-fix

#198 Add iochaos configmap
  chaosfs/pd-configmap.yaml
  chaosfs/tiflash-configmap.yaml
  chaosfs/tikv-configmap.yaml
Labels: status/can-merge

#188 update graph.go
  pkg/elle/core/graph.go
Labels: status/can-merge

#200 tidb_cluster: use UTC timezone
  pkg/test-infra/tidb/recommend.go
Labels: status/can-merge

#201 Fix the core problem and develop logic
  pkg/elle/core/check.go
  pkg/elle/core/core.go
  pkg/elle/core/core_test.go
  pkg/elle/core/graph.go
  pkg/elle/core/history.go
  pkg/elle/core/history_test.go
  pkg/elle/core/optional.go
  pkg/elle/txn/helper_fn.go
  pkg/elle/txn/txn_test.go
Labels: status/WIP
